# Assignment 2: Matrix Algebra and Data Manipulation

OPIM 5894 Data Science with Python

Name:   NetID:

Discussed with: if any

## Instructions
-  Always print out the results of each step. <br>
-  Before you start working on the assignment, it is helpful to get familiar with keyboard shortcuts (under Help menu). <br>
-  Don't get panic if you find something not demonstrated in class. Your best friend Google is there for you.
-  When you are done, go to the Notebook Menu Cell -> Run All, to run the code from beginning to end. <br>
-  Save the notebook file as both lastname.ipynb and lastname.html. Submit them and wide.csv to HuskyCT.<br>

You are supposed to finish this assignment on your own. If you have to discuss with others, please mention who you have discussed with on each question. Honesty is highly appreciated, so there is no penalty for disclosing such information.

## 1. Linear Algebra
### Goal: understand the basics of matrix algebra with a toy example

In [27]:
import numpy as np

1.1 Generate a numpy array with 16 random normally distributed numbers.
Set the seed of random number generator to the five digits of your netid (removing leading 0)

In [28]:
np.random.seed(16107)
v = np.random.randn(16)
v

array([ 1.60060759,  0.98690572,  0.05787913, -0.02024822, -0.2360482 ,
        1.10762526,  0.12673864,  0.58477305,  0.23765014,  1.17541464,
        1.11893338,  0.73556381, -1.02540331,  1.05952316,  0.02091303,
       -1.33840768])

1.2 Reshape the numpy array to a 4*4 matrix M

In [29]:
M = v.reshape((4,4))
M

array([[ 1.60060759,  0.98690572,  0.05787913, -0.02024822],
       [-0.2360482 ,  1.10762526,  0.12673864,  0.58477305],
       [ 0.23765014,  1.17541464,  1.11893338,  0.73556381],
       [-1.02540331,  1.05952316,  0.02091303, -1.33840768]])

1.3 Compute the determinant and rank of the matrix

In [30]:
np.linalg.det(M)

-4.2177094124730496

In [31]:
np.linalg.matrix_rank(M)

4

1.4 Check if A=MM' and B=M'M are the same (difference no more than 1e-6 on each element)

In [32]:
A = M.dot(M.T)
A

array([[ 3.53968754,  0.71079606,  1.59027708, -0.56730806],
       [ 0.71079606,  1.64057467,  1.81777204,  0.63558497],
       [ 1.59027708,  1.81777204,  3.2311432 ,  0.04060784],
       [-0.56730806,  0.63558497,  0.04060784,  3.96581373]])

In [33]:
B = M.T.dot(M)
B

array([[ 3.72559295,  0.51109473,  0.30719573,  1.37677042],
       [ 0.51109473,  4.70500551,  1.53486868,  0.07424486],
       [ 0.30719573,  1.53486868,  1.27186194,  0.86799812],
       [ 1.37677042,  0.07424486,  0.86799812,  2.67475873]])

In [34]:
C = abs(A-B)<1e-6
C.all()

False

1.5 Compute the inverse of the matrix A=MM'

In [35]:
Ai = np.linalg.inv(A)
Ai

array([[ 0.37686822,  0.06706042, -0.22378187,  0.04545475],
       [ 0.06706042,  1.92306092, -1.11126837, -0.28722945],
       [-0.22378187, -1.11126837,  1.04310116,  0.13540579],
       [ 0.04545475, -0.28722945,  0.13540579,  0.30330397]])

1.6 Compute the product of A and its inverse (if exists)

In [36]:
A.dot(Ai)

array([[  1.00000000e+00,   0.00000000e+00,  -1.11022302e-16,
          0.00000000e+00],
       [ -5.55111512e-17,   1.00000000e+00,   2.22044605e-16,
          5.55111512e-17],
       [ -5.55111512e-17,   0.00000000e+00,   1.00000000e+00,
          1.11022302e-16],
       [  8.32667268e-17,  -4.16333634e-17,  -8.32667268e-17,
          1.00000000e+00]])

1.7 Set the diagnal elements of matrix M to 0. What are the determinant and rank of M now?

In [37]:
np.fill_diagonal(M, 0)
M

array([[ 0.        ,  0.98690572,  0.05787913, -0.02024822],
       [-0.2360482 ,  0.        ,  0.12673864,  0.58477305],
       [ 0.23765014,  1.17541464,  0.        ,  0.73556381],
       [-1.02540331,  1.05952316,  0.02091303,  0.        ]])

In [38]:
np.linalg.det(M)

0.15147458270447686

In [39]:
np.linalg.matrix_rank(M)

4

1.8 Multiple matrix M in 1.7 by a matrix X (on the left or right), such that every element in the i-th column is multiplied by scalar i (i=1,2,3,4)

In [40]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [41]:
M.dot(np.diag([1, 2, 3, 4]))

array([[ 0.        ,  1.97381143,  0.17363738, -0.08099289],
       [-0.2360482 ,  0.        ,  0.38021592,  2.33909219],
       [ 0.23765014,  2.35082929,  0.        ,  2.94225522],
       [-1.02540331,  2.11904631,  0.0627391 ,  0.        ]])

1.9 Multiple matrix M in 1.7 by a matrix X (on the left or right), such that every element in the i-th row is multiplied by scalar i (i=1,2,3,4)

In [42]:
np.diag([1, 2, 3, 4]).dot(M)

array([[ 0.        ,  0.98690572,  0.05787913, -0.02024822],
       [-0.47209641,  0.        ,  0.25347728,  1.16954609],
       [ 0.71295043,  3.52624393,  0.        ,  2.20669142],
       [-4.10161324,  4.23809262,  0.08365213,  0.        ]])

## 2. Data Manipulation
### Goal: learn to deal with real-world datasets, using Stock Market Indexes as an example.
Source: https://fred.stlouisfed.org/categories/32255/downloaddata

### 2.1 Load Multiple Stock Market Index files into Python

a. change working directory to the location of files on YOUR computer

In [44]:
import os
import pandas as pd
os.chdir('D:/Dropbox/Teaching/Data Science using Python/Assignments/Assignment2')

b. list all files under the given location

In [46]:
files = os.listdir()
files

['Assignment2.ipynb',
 'DJCA.txt',
 'DJIA.txt',
 'DJTA.txt',
 'DJUA.txt',
 'NASDAQ100.txt',
 'NASDAQCOM.txt',
 'original',
 'SP500.txt',
 'wide.csv']

In [47]:
files = [f for f in files if f.endswith('.txt')]
files

['DJCA.txt',
 'DJIA.txt',
 'DJTA.txt',
 'DJUA.txt',
 'NASDAQ100.txt',
 'NASDAQCOM.txt',
 'SP500.txt']

c. load all the TEXT files as data frames

In [54]:
frames = [pd.read_table(f, na_values='.', delim_whitespace=True) for f in files if f.endswith('.txt')]
keys = [f[:-4] for f in files if f.endswith('.txt')]

In [55]:
keys

['DJCA', 'DJIA', 'DJTA', 'DJUA', 'NASDAQ100', 'NASDAQCOM', 'SP500']

In [56]:
frames2 = {f[:-4]: pd.read_table(f, na_values='.', delim_whitespace=True) 
           for f in files if f.endswith('.txt')}

In [52]:
frames2.keys()

dict_keys(['DJCA.txt', 'DJIA.txt', 'DJTA.txt', 'DJUA.txt', 'NASDAQ100.txt', 'NASDAQCOM.txt', 'SP500.txt'])

In [53]:
frames2['DJCA.txt']

DATE    VALUE
0     2007-09-17  4394.42
1     2007-09-18  4518.35
2     2007-09-19  4535.64
3     2007-09-20  4491.60
4     2007-09-21  4508.88
5     2007-09-24  4484.37
6     2007-09-25  4497.22
7     2007-09-26  4527.18
8     2007-09-27  4530.51
9     2007-09-28  4510.86
10    2007-10-01  4575.48
11    2007-10-02  4571.31
12    2007-10-03  4537.24
13    2007-10-04  4544.73
14    2007-10-05  4607.63
15    2007-10-08  4585.09
16    2007-10-09  4631.86
17    2007-10-10  4594.40
18    2007-10-11  4575.79
19    2007-10-12  4604.88
20    2007-10-15  4563.25
21    2007-10-16  4534.14
22    2007-10-17  4541.78
23    2007-10-18  4546.26
24    2007-10-19  4435.56
25    2007-10-22  4460.87
26    2007-10-23  4505.42
27    2007-10-24  4498.20
28    2007-10-25  4497.76
29    2007-10-26  4544.35
...          ...      ...
2580  2017-08-07  7535.14
2581  2017-08-08  7520.96
2582  2017-08-09  7509.73
2583  2017-08-10  7447.86
2584  2017-08-11  7460.86
2585  2017-08-14  7525.80
2586  2017-08-15  7537.46
2587  2017-08-16  7547.29
2588  2017-08-17  7436.53
2589  2017-08-18  7415.96
2590  2017-08-21  7432.50
2591  2017-08-22  7490.65
2592  2017-08-23  7450.06
2593  2017-08-24  7429.05
2594  2017-08-25  7464.85
2595  2017-08-28  7471.69
2596  2017-08-29  7497.37
2597  2017-08-30  7512.88
2598  2017-08-31  7525.81
2599  2017-09-01  7537.65
2600  2017-09-04      NaN
2601  2017-09-05  7476.16
2602  2017-09-06  7488.76
2603  2017-09-07  7501.28
2604  2017-09-08  7517.12
2605  2017-09-11  7602.33
2606  2017-09-12  7606.18
2607  2017-09-13  7605.09
2608  2017-09-14  7619.82
2609  2017-09-15  7642.37

[2610 rows x 2 columns]

### 2.2 Data Exploration

a. For each dataset, check the numbers of observations and missing values. Summarize the results in a easy to read format, such as a dictionary, matrix or data frame

In [57]:
obs = [[len(df.index),np.count_nonzero(np.isnan(df.VALUE))]  for df in frames]
obs = pd.DataFrame(obs, index=keys, columns=['obs','missing'])
obs

obs  missing
DJCA        2610       91
DJIA        2610       91
DJTA        2610       91
DJUA        2610       91
NASDAQ100   8272      278
NASDAQCOM  12161      402
SP500       2621       92

b. Extract the observations between 2017-08-01 and 2017-08-31 for each dataset. <br>
You will work on the extracted subsets from now on

In [58]:
for df in frames: df.DATE = pd.to_datetime(df.DATE)

In [20]:
subframes = [df[df.DATE.isin(pd.date_range('2017-08-01','2017-08-31')) ] for df in frames]
subframes[6]

DATE    VALUE
2587 2017-08-01  2476.35
2588 2017-08-02  2477.57
2589 2017-08-03  2472.16
2590 2017-08-04  2476.83
2591 2017-08-07  2480.91
2592 2017-08-08  2474.92
2593 2017-08-09  2474.02
2594 2017-08-10  2438.21
2595 2017-08-11  2441.32
2596 2017-08-14  2465.84
2597 2017-08-15  2464.61
2598 2017-08-16  2468.11
2599 2017-08-17  2430.01
2600 2017-08-18  2425.55
2601 2017-08-21  2428.37
2602 2017-08-22  2452.51
2603 2017-08-23  2444.04
2604 2017-08-24  2438.97
2605 2017-08-25  2443.05
2606 2017-08-28  2444.24
2607 2017-08-29  2446.30
2608 2017-08-30  2457.59
2609 2017-08-31  2471.65

c. summarize the descriptive stats (pd.describe) of the datasets in a easy to read format, such as a dictionary, matrix or data frame

In [21]:
pd.concat([df.describe() for df in subframes], axis=1, keys=keys)

DJCA          DJIA         DJTA        DJUA    NASDAQ100  \
             VALUE         VALUE        VALUE       VALUE        VALUE   
count    23.000000     23.000000    23.000000   23.000000    23.000000   
mean   7486.701739  21914.076957  9208.830435  738.156522  5874.416957   
std      39.471402    128.223965    96.362522    5.739175    55.679825   
min    7415.960000  21674.510000  9021.120000  728.850000  5786.540000   
25%    7455.460000  21812.880000  9139.750000  733.850000  5832.985000   
50%    7490.650000  21899.890000  9200.940000  737.550000  5891.200000   
75%    7523.365000  22020.555000  9281.145000  743.210000  5915.825000   
max    7547.290000  22118.420000  9377.220000  748.160000  5988.600000   

         NASDAQCOM        SP500  
             VALUE        VALUE  
count    23.000000    23.000000  
mean   6311.397391  2456.223043  
std      61.067734    18.071766  
min    6213.130000  2425.550000  
25%    6268.485000  2442.185000  
50%    6333.010000  2457.590000  
75%    6357.490000  2473.090000  
max    6428.660000  2480.910000

### 2.3 Concatenation

a. Concat the extracted datasets, along the rows, to one big data frame. Add a column to indicate which Stock Market Index each observation is about

In [22]:
df1 = pd.concat(subframes, ignore_index=True)
df1['SI'] = np.repeat(keys, [len(df.index) for df in subframes])
df1

DATE     VALUE         SI
0   2017-08-01   7467.02       DJCA
1   2017-08-02   7488.68       DJCA
2   2017-08-03   7500.22       DJCA
3   2017-08-04   7525.77       DJCA
4   2017-08-07   7535.14       DJCA
5   2017-08-08   7520.96       DJCA
6   2017-08-09   7509.73       DJCA
7   2017-08-10   7447.86       DJCA
8   2017-08-11   7460.86       DJCA
9   2017-08-14   7525.80       DJCA
10  2017-08-15   7537.46       DJCA
11  2017-08-16   7547.29       DJCA
12  2017-08-17   7436.53       DJCA
13  2017-08-18   7415.96       DJCA
14  2017-08-21   7432.50       DJCA
15  2017-08-22   7490.65       DJCA
16  2017-08-23   7450.06       DJCA
17  2017-08-24   7429.05       DJCA
18  2017-08-25   7464.85       DJCA
19  2017-08-28   7471.69       DJCA
20  2017-08-29   7497.37       DJCA
21  2017-08-30   7512.88       DJCA
22  2017-08-31   7525.81       DJCA
23  2017-08-01  21963.92       DJIA
24  2017-08-02  22016.24       DJIA
25  2017-08-03  22026.10       DJIA
26  2017-08-04  22092.81       DJIA
27  2017-08-07  22118.42       DJIA
28  2017-08-08  22085.34       DJIA
29  2017-08-09  22048.70       DJIA
..         ...       ...        ...
131 2017-08-23   6278.41  NASDAQCOM
132 2017-08-24   6271.33  NASDAQCOM
133 2017-08-25   6265.64  NASDAQCOM
134 2017-08-28   6283.02  NASDAQCOM
135 2017-08-29   6301.89  NASDAQCOM
136 2017-08-30   6368.31  NASDAQCOM
137 2017-08-31   6428.66  NASDAQCOM
138 2017-08-01   2476.35      SP500
139 2017-08-02   2477.57      SP500
140 2017-08-03   2472.16      SP500
141 2017-08-04   2476.83      SP500
142 2017-08-07   2480.91      SP500
143 2017-08-08   2474.92      SP500
144 2017-08-09   2474.02      SP500
145 2017-08-10   2438.21      SP500
146 2017-08-11   2441.32      SP500
147 2017-08-14   2465.84      SP500
148 2017-08-15   2464.61      SP500
149 2017-08-16   2468.11      SP500
150 2017-08-17   2430.01      SP500
151 2017-08-18   2425.55      SP500
152 2017-08-21   2428.37      SP500
153 2017-08-22   2452.51      SP500
154 2017-08-23   2444.04      SP500
155 2017-08-24   2438.97      SP500
156 2017-08-25   2443.05      SP500
157 2017-08-28   2444.24      SP500
158 2017-08-29   2446.30      SP500
159 2017-08-30   2457.59      SP500
160 2017-08-31   2471.65      SP500

[161 rows x 3 columns]

b. The resulting dataset above is in a long format. Now convert it into a wide format, with row labels being dates and column labels being names of Stock Market Indexes

In [23]:
df1.pivot(index='DATE',columns='SI',values='VALUE')

SI             DJCA      DJIA     DJTA    DJUA  NASDAQ100  NASDAQCOM    SP500
DATE                                                                         
2017-08-01  7467.02  21963.92  9145.75  728.85    5895.17    6362.94  2476.35
2017-08-02  7488.68  22016.24  9174.99  731.93    5914.23    6362.65  2477.57
2017-08-03  7500.22  22026.10  9202.40  734.11    5891.20    6340.34  2472.16
2017-08-04  7525.77  22092.81  9277.63  731.87    5899.91    6351.56  2476.83
2017-08-07  7535.14  22118.42  9284.66  733.59    5934.73    6383.77  2480.91
2017-08-08  7520.96  22085.34  9232.85  735.68    5926.35    6370.46  2474.92
2017-08-09  7509.73  22048.70  9235.41  732.89    5919.39    6352.33  2474.02
2017-08-10  7447.86  21844.01  9119.74  734.65    5788.19    6216.87  2438.21
2017-08-11  7460.86  21858.32  9199.05  730.45    5831.53    6256.56  2441.32
2017-08-14  7525.80  21993.71  9347.55  734.26    5908.17    6340.23  2465.84
2017-08-15  7537.46  21998.99  9371.07  737.55    5907.73    6333.01  2464.61
2017-08-16  7547.29  22024.87  9377.22  739.62    5917.42    6345.11  2468.11
2017-08-17  7436.53  21750.73  9152.45  734.42    5796.32    6221.91  2430.01
2017-08-18  7415.96  21674.51  9095.31  738.38    5790.91    6216.53  2425.55
2017-08-21  7432.50  21703.75  9121.93  741.41    5786.54    6213.13  2428.37
2017-08-22  7490.65  21899.89  9200.94  743.18    5873.33    6297.48  2452.51
2017-08-23  7450.06  21812.09  9086.30  744.00    5851.78    6278.41  2444.04
2017-08-24  7429.05  21783.40  9021.12  743.25    5834.44    6271.33  2438.97
2017-08-25  7464.85  21813.67  9133.75  746.48    5822.53    6265.64  2443.05
2017-08-28  7471.69  21808.40  9156.96  748.16    5838.08    6283.02  2444.24
2017-08-29  7497.37  21865.37  9237.18  746.47    5862.14    6301.89  2446.30
2017-08-30  7512.88  21892.43  9309.79  743.16    5932.90    6368.31  2457.59
2017-08-31  7525.81  21948.10  9319.05  743.24    5988.60    6428.66  2471.65

### 2.4 Merging Data

a. Merge the extracted datasets into one data frame. The resulting data frame should be in a wide format with one column labeled by Date and the rest columns labeled being names of Stock Market Indexes 

In [24]:
subframes = [df.rename(columns={'VALUE':key}) for key, df in zip(keys, subframes)]

In [25]:
df2 = subframes[0]
for i in range(1,len(subframes)): df2 = df2.merge(subframes[i], on='DATE')
df2

DATE     DJCA      DJIA     DJTA    DJUA  NASDAQ100  NASDAQCOM  \
0  2017-08-01  7467.02  21963.92  9145.75  728.85    5895.17    6362.94   
1  2017-08-02  7488.68  22016.24  9174.99  731.93    5914.23    6362.65   
2  2017-08-03  7500.22  22026.10  9202.40  734.11    5891.20    6340.34   
3  2017-08-04  7525.77  22092.81  9277.63  731.87    5899.91    6351.56   
4  2017-08-07  7535.14  22118.42  9284.66  733.59    5934.73    6383.77   
5  2017-08-08  7520.96  22085.34  9232.85  735.68    5926.35    6370.46   
6  2017-08-09  7509.73  22048.70  9235.41  732.89    5919.39    6352.33   
7  2017-08-10  7447.86  21844.01  9119.74  734.65    5788.19    6216.87   
8  2017-08-11  7460.86  21858.32  9199.05  730.45    5831.53    6256.56   
9  2017-08-14  7525.80  21993.71  9347.55  734.26    5908.17    6340.23   
10 2017-08-15  7537.46  21998.99  9371.07  737.55    5907.73    6333.01   
11 2017-08-16  7547.29  22024.87  9377.22  739.62    5917.42    6345.11   
12 2017-08-17  7436.53  21750.73  9152.45  734.42    5796.32    6221.91   
13 2017-08-18  7415.96  21674.51  9095.31  738.38    5790.91    6216.53   
14 2017-08-21  7432.50  21703.75  9121.93  741.41    5786.54    6213.13   
15 2017-08-22  7490.65  21899.89  9200.94  743.18    5873.33    6297.48   
16 2017-08-23  7450.06  21812.09  9086.30  744.00    5851.78    6278.41   
17 2017-08-24  7429.05  21783.40  9021.12  743.25    5834.44    6271.33   
18 2017-08-25  7464.85  21813.67  9133.75  746.48    5822.53    6265.64   
19 2017-08-28  7471.69  21808.40  9156.96  748.16    5838.08    6283.02   
20 2017-08-29  7497.37  21865.37  9237.18  746.47    5862.14    6301.89   
21 2017-08-30  7512.88  21892.43  9309.79  743.16    5932.90    6368.31   
22 2017-08-31  7525.81  21948.10  9319.05  743.24    5988.60    6428.66   

      SP500  
0   2476.35  
1   2477.57  
2   2472.16  
3   2476.83  
4   2480.91  
5   2474.92  
6   2474.02  
7   2438.21  
8   2441.32  
9   2465.84  
10  2464.61  
11  2468.11  
12  2430.01  
13  2425.55  
14  2428.37  
15  2452.51  
16  2444.04  
17  2438.97  
18  2443.05  
19  2444.24  
20  2446.30  
21  2457.59  
22  2471.65

b. Convert the wide format dataset above into a long format

In [26]:
df2.melt(id_vars='DATE')

DATE   variable     value
0   2017-08-01       DJCA   7467.02
1   2017-08-02       DJCA   7488.68
2   2017-08-03       DJCA   7500.22
3   2017-08-04       DJCA   7525.77
4   2017-08-07       DJCA   7535.14
5   2017-08-08       DJCA   7520.96
6   2017-08-09       DJCA   7509.73
7   2017-08-10       DJCA   7447.86
8   2017-08-11       DJCA   7460.86
9   2017-08-14       DJCA   7525.80
10  2017-08-15       DJCA   7537.46
11  2017-08-16       DJCA   7547.29
12  2017-08-17       DJCA   7436.53
13  2017-08-18       DJCA   7415.96
14  2017-08-21       DJCA   7432.50
15  2017-08-22       DJCA   7490.65
16  2017-08-23       DJCA   7450.06
17  2017-08-24       DJCA   7429.05
18  2017-08-25       DJCA   7464.85
19  2017-08-28       DJCA   7471.69
20  2017-08-29       DJCA   7497.37
21  2017-08-30       DJCA   7512.88
22  2017-08-31       DJCA   7525.81
23  2017-08-01       DJIA  21963.92
24  2017-08-02       DJIA  22016.24
25  2017-08-03       DJIA  22026.10
26  2017-08-04       DJIA  22092.81
27  2017-08-07       DJIA  22118.42
28  2017-08-08       DJIA  22085.34
29  2017-08-09       DJIA  22048.70
..         ...        ...       ...
131 2017-08-23  NASDAQCOM   6278.41
132 2017-08-24  NASDAQCOM   6271.33
133 2017-08-25  NASDAQCOM   6265.64
134 2017-08-28  NASDAQCOM   6283.02
135 2017-08-29  NASDAQCOM   6301.89
136 2017-08-30  NASDAQCOM   6368.31
137 2017-08-31  NASDAQCOM   6428.66
138 2017-08-01      SP500   2476.35
139 2017-08-02      SP500   2477.57
140 2017-08-03      SP500   2472.16
141 2017-08-04      SP500   2476.83
142 2017-08-07      SP500   2480.91
143 2017-08-08      SP500   2474.92
144 2017-08-09      SP500   2474.02
145 2017-08-10      SP500   2438.21
146 2017-08-11      SP500   2441.32
147 2017-08-14      SP500   2465.84
148 2017-08-15      SP500   2464.61
149 2017-08-16      SP500   2468.11
150 2017-08-17      SP500   2430.01
151 2017-08-18      SP500   2425.55
152 2017-08-21      SP500   2428.37
153 2017-08-22      SP500   2452.51
154 2017-08-23      SP500   2444.04
155 2017-08-24      SP500   2438.97
156 2017-08-25      SP500   2443.05
157 2017-08-28      SP500   2444.24
158 2017-08-29      SP500   2446.30
159 2017-08-30      SP500   2457.59
160 2017-08-31      SP500   2471.65

[161 rows x 3 columns]

c. Back to the wide format data frame, set the DATE column as index (row labels).

In [27]:
df3 = df2.set_index('DATE')
df3

DJCA      DJIA     DJTA    DJUA  NASDAQ100  NASDAQCOM    SP500
DATE                                                                         
2017-08-01  7467.02  21963.92  9145.75  728.85    5895.17    6362.94  2476.35
2017-08-02  7488.68  22016.24  9174.99  731.93    5914.23    6362.65  2477.57
2017-08-03  7500.22  22026.10  9202.40  734.11    5891.20    6340.34  2472.16
2017-08-04  7525.77  22092.81  9277.63  731.87    5899.91    6351.56  2476.83
2017-08-07  7535.14  22118.42  9284.66  733.59    5934.73    6383.77  2480.91
2017-08-08  7520.96  22085.34  9232.85  735.68    5926.35    6370.46  2474.92
2017-08-09  7509.73  22048.70  9235.41  732.89    5919.39    6352.33  2474.02
2017-08-10  7447.86  21844.01  9119.74  734.65    5788.19    6216.87  2438.21
2017-08-11  7460.86  21858.32  9199.05  730.45    5831.53    6256.56  2441.32
2017-08-14  7525.80  21993.71  9347.55  734.26    5908.17    6340.23  2465.84
2017-08-15  7537.46  21998.99  9371.07  737.55    5907.73    6333.01  2464.61
2017-08-16  7547.29  22024.87  9377.22  739.62    5917.42    6345.11  2468.11
2017-08-17  7436.53  21750.73  9152.45  734.42    5796.32    6221.91  2430.01
2017-08-18  7415.96  21674.51  9095.31  738.38    5790.91    6216.53  2425.55
2017-08-21  7432.50  21703.75  9121.93  741.41    5786.54    6213.13  2428.37
2017-08-22  7490.65  21899.89  9200.94  743.18    5873.33    6297.48  2452.51
2017-08-23  7450.06  21812.09  9086.30  744.00    5851.78    6278.41  2444.04
2017-08-24  7429.05  21783.40  9021.12  743.25    5834.44    6271.33  2438.97
2017-08-25  7464.85  21813.67  9133.75  746.48    5822.53    6265.64  2443.05
2017-08-28  7471.69  21808.40  9156.96  748.16    5838.08    6283.02  2444.24
2017-08-29  7497.37  21865.37  9237.18  746.47    5862.14    6301.89  2446.30
2017-08-30  7512.88  21892.43  9309.79  743.16    5932.90    6368.31  2457.59
2017-08-31  7525.81  21948.10  9319.05  743.24    5988.60    6428.66  2471.65

d. Add weekend dates to the data frame in step c, set the values on weekends as 0.

In [28]:
df4 = df3.reindex(index=pd.date_range('2017-08-01','2017-08-31'), fill_value=0)
df4

DJCA      DJIA     DJTA    DJUA  NASDAQ100  NASDAQCOM    SP500
2017-08-01  7467.02  21963.92  9145.75  728.85    5895.17    6362.94  2476.35
2017-08-02  7488.68  22016.24  9174.99  731.93    5914.23    6362.65  2477.57
2017-08-03  7500.22  22026.10  9202.40  734.11    5891.20    6340.34  2472.16
2017-08-04  7525.77  22092.81  9277.63  731.87    5899.91    6351.56  2476.83
2017-08-05     0.00      0.00     0.00    0.00       0.00       0.00     0.00
2017-08-06     0.00      0.00     0.00    0.00       0.00       0.00     0.00
2017-08-07  7535.14  22118.42  9284.66  733.59    5934.73    6383.77  2480.91
2017-08-08  7520.96  22085.34  9232.85  735.68    5926.35    6370.46  2474.92
2017-08-09  7509.73  22048.70  9235.41  732.89    5919.39    6352.33  2474.02
2017-08-10  7447.86  21844.01  9119.74  734.65    5788.19    6216.87  2438.21
2017-08-11  7460.86  21858.32  9199.05  730.45    5831.53    6256.56  2441.32
2017-08-12     0.00      0.00     0.00    0.00       0.00       0.00     0.00
2017-08-13     0.00      0.00     0.00    0.00       0.00       0.00     0.00
2017-08-14  7525.80  21993.71  9347.55  734.26    5908.17    6340.23  2465.84
2017-08-15  7537.46  21998.99  9371.07  737.55    5907.73    6333.01  2464.61
2017-08-16  7547.29  22024.87  9377.22  739.62    5917.42    6345.11  2468.11
2017-08-17  7436.53  21750.73  9152.45  734.42    5796.32    6221.91  2430.01
2017-08-18  7415.96  21674.51  9095.31  738.38    5790.91    6216.53  2425.55
2017-08-19     0.00      0.00     0.00    0.00       0.00       0.00     0.00
2017-08-20     0.00      0.00     0.00    0.00       0.00       0.00     0.00
2017-08-21  7432.50  21703.75  9121.93  741.41    5786.54    6213.13  2428.37
2017-08-22  7490.65  21899.89  9200.94  743.18    5873.33    6297.48  2452.51
2017-08-23  7450.06  21812.09  9086.30  744.00    5851.78    6278.41  2444.04
2017-08-24  7429.05  21783.40  9021.12  743.25    5834.44    6271.33  2438.97
2017-08-25  7464.85  21813.67  9133.75  746.48    5822.53    6265.64  2443.05
2017-08-26     0.00      0.00     0.00    0.00       0.00       0.00     0.00
2017-08-27     0.00      0.00     0.00    0.00       0.00       0.00     0.00
2017-08-28  7471.69  21808.40  9156.96  748.16    5838.08    6283.02  2444.24
2017-08-29  7497.37  21865.37  9237.18  746.47    5862.14    6301.89  2446.30
2017-08-30  7512.88  21892.43  9309.79  743.16    5932.90    6368.31  2457.59
2017-08-31  7525.81  21948.10  9319.05  743.24    5988.60    6428.66  2471.65

e. Save the wide format dataset above as wide.csv, respectively. Submit the data on HusckCT as well

In [29]:
df4.to_csv("wide.csv")

### 2.5 Analyzing Data
The analysis below focuses on the wide format data frame generated in step 2.4.c 

a. Compute the correlation matrix of the seven Stock Market Indexes

In [30]:
df3.corr()

DJCA      DJIA      DJTA      DJUA  NASDAQ100  NASDAQCOM  \
DJCA       1.000000  0.868147  0.919986 -0.144886   0.867959   0.834735   
DJIA       0.868147  1.000000  0.674880 -0.491723   0.818658   0.834817   
DJTA       0.919986  0.674880  1.000000 -0.148850   0.738423   0.672491   
DJUA      -0.144886 -0.491723 -0.148850  1.000000  -0.162799  -0.197003   
NASDAQ100  0.867959  0.818658  0.738423 -0.162799   1.000000   0.985068   
NASDAQCOM  0.834735  0.834817  0.672491 -0.197003   0.985068   1.000000   
SP500      0.824672  0.957035  0.623126 -0.446223   0.891543   0.925915   

              SP500  
DJCA       0.824672  
DJIA       0.957035  
DJTA       0.623126  
DJUA      -0.446223  
NASDAQ100  0.891543  
NASDAQCOM  0.925915  
SP500      1.000000

b. Convert pandas data frame to a numpy Matrix and then compute its condition number. Do you think if there are multicolinearity issue? Provide your answer in commments.

In [31]:
mat = np.matrix(df3.as_matrix())
mat

matrix([[  7467.02,  21963.92,   9145.75,    728.85,   5895.17,   6362.94,
           2476.35],
        [  7488.68,  22016.24,   9174.99,    731.93,   5914.23,   6362.65,
           2477.57],
        [  7500.22,  22026.1 ,   9202.4 ,    734.11,   5891.2 ,   6340.34,
           2472.16],
        [  7525.77,  22092.81,   9277.63,    731.87,   5899.91,   6351.56,
           2476.83],
        [  7535.14,  22118.42,   9284.66,    733.59,   5934.73,   6383.77,
           2480.91],
        [  7520.96,  22085.34,   9232.85,    735.68,   5926.35,   6370.46,
           2474.92],
        [  7509.73,  22048.7 ,   9235.41,    732.89,   5919.39,   6352.33,
           2474.02],
        [  7447.86,  21844.01,   9119.74,    734.65,   5788.19,   6216.87,
           2438.21],
        [  7460.86,  21858.32,   9199.05,    730.45,   5831.53,   6256.56,
           2441.32],
        [  7525.8 ,  21993.71,   9347.55,    734.26,   5908.17,   6340.23,
           2465.84],
        [  7537.46,  21998.99,   9371.07

In [32]:
np.linalg.cond(mat)

11939651.179439247